### ISSUE TITLE
"Unsupported inverter type 702 please create GitHub issue."

### ISSUE THREAD

**Issue by codeman256** [ksheumaker/homeassistant-apsystems_ecur#102]
Tried adding integration to HA but got the following error (from logs)

Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.apsystems_ecur.config_flow
Source: custom_components/apsystems_ecur/APSystemsSocket.py:348
Integration: APSystems PV solar ECU ([documentation](https://github.com/ksheumaker/homeassistant-apsystems_ecur))
First occurred: 8:51:01 PM (1 occurrences)
Last logged: 8:51:01 PM

APSystemsInvalidData exception: Unsupported inverter type 702 please create GitHub issue.
Traceback (most recent call last):
  File "/config/custom_components/apsystems_ecur/config_flow.py", line 45, in async_step_user
    test_query = await self.hass.async_add_executor_job(ap_ecu.query_ecu)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/apsystems_ecur/APSystemsSocket.py", line 158, in query_ecu
    data = self.process_inverter_data()
  File "/config/custom_components/apsystems_ecur/APSystemsSocket.py", line 348, in process_inverter_data
    raise APSystemsInvalidData(error)
custom_components.apsystems_ecur.APSystemsSocket.APSystemsInvalidData: Unsupported inverter type 702 please create GitHub issue.

**Comment by codeman256** [comment]
nvm. just found discussion: https://github.com/ksheumaker/homeassistant-apsystems_ecur/discussions/95
will mark as solved
