### ISSUE TITLE
Failed to start integration after HA 2023.5.0 upgrade

### ISSUE THREAD

**Issue by Verguldebarman** [ksheumaker/homeassistant-apsystems_ecur#186]
Error with integration after upgrade to Home Assistant 2023.5.0.

I have the following error and the integration failed to start:

 ```This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/apsystems_ecur/__init__.py:187
Integration: APSystems PV solar ECU (documentation, issues)
First occurred: 08:44:55 (1 occurrences)
Last logged: 08:44:55

Error setting up entry APsystems for apsystems_ecur
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/apsystems_ecur/__init__.py", line 187, in async_setup_entry
    hass.config_entries.async_setup_platforms(config, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by Verguldebarman** [comment]
Downgraded to Home Assistant 2023.4.6 solved the issue, so something seams to have changed in the latest HA version.

**Comment by Verguldebarman** [comment]
> Are you on the latest version? I've just upgraded my HA to 2023.5.0 and i don't get this error..

Dumb me..... I thought I updated it, but apparently forgot. 
Upgrading to version v1.2.29 did the trick indeed!

Issue solved!
