### ISSUE TITLE
Unhandled exception: 'APSystemsECUR' object has no attribute 'socket_close'

### ISSUE THREAD

**Issue by edgarvoorbraak** [ksheumaker/homeassistant-apsystems_ecur#65]
Hi I have a new installation with an ecu-b and a ds3-l attached. Note that there is only 1 of the 2 panels attached, so I am running with only 1 solarpanel.
The ecu is running and i see values of the panel in the APS app.

I installed 1.2.11, upon entering the IP address i get the following error in the logging: 

Unhandled exception: 'APSystemsECUR' object has no attribute 'socket_close'
Traceback (most recent call last):
  File "/config/custom_components/apsystems_ecur/config_flow.py", line 45, in async_step_user
    test_query = await self.hass.async_add_executor_job(ap_ecu.query_ecu)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/apsystems_ecur/APSystemsECUR.py", line 180, in query_ecu
    self.socket_close()
AttributeError: 'APSystemsECUR' object has no attribute 'socket_close'

downgrading using 1.2.10 using the method mentioned in HA forum, does not have any influence on this error.

**Comment by edgarvoorbraak** [comment]
Hi HAEdwin,

Thanks, that helped! So most likely this was due to me not restarting HA after installing the integration from HACS.

Cheers.
