### ISSUE TITLE
ECU-R Can't Connect - Inverter Type 702

### ISSUE THREAD

**Issue by esloyer** [ksheumaker/homeassistant-apsystems_ecur#83]
Hello, first of all, thank you for creating this integration, I'm excited to have my ECU-R data in HomeAssistant.

I have 23 DS3-S inverters of type 702, however, when trying to connect, I get an error as seen below. Any advice?

`Logger: custom_components.apsystems_ecur.config_flow
Source: custom_components/apsystems_ecur/APSystemsSocket.py:348
Integration: APSystems PV solar ECU ([documentation](https://github.com/ksheumaker/homeassistant-apsystems_ecur))
First occurred: 7:20:50 AM (1 occurrences)
Last logged: 7:20:50 AM

APSystemsInvalidData exception: Unsupported inverter type 702 please create GitHub issue.
Traceback (most recent call last):
  File "/config/custom_components/apsystems_ecur/config_flow.py", line 45, in async_step_user
    test_query = await self.hass.async_add_executor_job(ap_ecu.query_ecu)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/apsystems_ecur/APSystemsSocket.py", line 158, in query_ecu
    data = self.process_inverter_data()
  File "/config/custom_components/apsystems_ecur/APSystemsSocket.py", line 348, in process_inverter_data
    raise APSystemsInvalidData(error)
custom_components.apsystems_ecur.APSystemsSocket.APSystemsInvalidData: Unsupported inverter type 702 please create GitHub issue.`

**Comment by esloyer** [comment]
It appears that the fork worked, thanks!
